app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/inner_db
      username: postgres
      password: '0000'
      pool-size: '30'
spring:
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
