 server:
  port: 8081
 spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: '0000'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
